type: perJet
cuts:
  - "(jets_eta<0.1) && (jets_eta>-0.1)"
  - "((jets_eta<0.3) && (jets_eta>0.1)) || ((jets_eta>-0.3) && (jets_eta<-0.1))"
  - "((jets_eta<0.5) && (jets_eta>0.3)) || ((jets_eta>-0.5) && (jets_eta<-0.3))"
  - "((jets_eta<0.7) && (jets_eta>0.5)) || ((jets_eta>-0.7) && (jets_eta<-0.5))"
  - "((jets_eta<0.9) && (jets_eta>0.7)) || ((jets_eta>-0.9) && (jets_eta<-0.7))"
  - "((jets_eta<1.1) && (jets_eta>0.9)) || ((jets_eta>-1.1) && (jets_eta<-0.9))"
  - "((jets_eta<1.3) && (jets_eta>1.1)) || ((jets_eta>-1.3) && (jets_eta<-1.1))"
  - "((jets_eta<1.5) && (jets_eta>1.3)) || ((jets_eta>-1.5) && (jets_eta<-1.3))"
  - "((jets_eta<1.7) && (jets_eta>1.5)) || ((jets_eta>-1.7) && (jets_eta<-1.5))"
  - "((jets_eta<1.9) && (jets_eta>1.7)) || ((jets_eta>-1.9) && (jets_eta<-1.7))"
  - "((jets_eta<2.1) && (jets_eta>1.9)) || ((jets_eta>-2.1) && (jets_eta<-1.9))"
  - "(jets_eta>2.1) || (jets_eta<-2.1)"

cut_names:
  - "0.0-0.1"
  - "0.1-0.3"
  - "0.3-0.5"
  - "0.5-0.7"
  - "0.7-0.9"
  - "0.9-1.1"
  - "1.1-1.3"
  - "1.3-1.5"
  - "1.5-1.7"
  - "1.7-1.9"
  - "1.9-2.1"
  - "2.1+"
