defaults:
  - data: pythia_allJZ
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] - %(message)s"
  output_subdir: config

data:
  path: data/sherpa_stepwise
logdir: logs/stepwise_flat/evaluation/sherpa
models_path: logs/stepwise_flat
seed: 42
draw_distribution: 
test_subfolder: test
batch_size: 384
take: 6_000
binning:
  variable: jets_pt
  bins: 20
  max_bin: 6_000_000
  min_bin: 20_000
  log_bin_base:
metrics_to_plot:
  [
    "gluon_efficiency",
    "quark_efficiency",
    "binary_accuracy",
    "auc",
    "effective_tagging_efficiency",
  ]
reference_model: transformer
ylims: # [[0, 1.1], [0, 1.1], [0.5, 1.1], [0.5, 1.1], [0.10, 0.5]]
model_names: [
    # "idepart",
    # "ipart",
    #
    # "idepart_rel",
    #
    "depart",
    # "part",
    "transformer",
    # "efn",
    # "pfn",
    #
    # "fc",
    # "highway",
  ]
model_input_types: [
    # "interaction_constituents",
    # "interaction_constituents",
    #
    # "irelative_constituents",
    #
    "constituents",
    "constituents",
    # "constituents",
    # "constituents",
    # "constituents",
    # #
    # "highlevel",
    # "highlevel",
  ]
threshold_path: /home/jankovys/JIDENN/logs/stepwise_flat/evaluation/pythia_th/models
threshold_var_name: threshold_at_fixed_quark_50wp
threshold_file_name: binned_metrics.csv
