LATEX_NAMING_CONVENTION = {
    'jets_ActiveArea4vec_m': 'jets_ActiveArea4vec_m',
    'jets_ActiveArea4vec_phi': 'jets_ActiveArea4vec_phi',
    'jets_ActiveArea4vec_eta': 'jets_ActiveArea4vec_eta',
    'jets_ActiveArea4vec_pt': 'jets_ActiveArea4vec_pt',
    'jets_DetectorEta': 'jets_DetectorEta',
    'jets_FracSamplingMax': 'jets_FracSamplingMax',
    'jets_FracSamplingMaxIndex': 'jets_FracSamplingMaxIndex',
    'jets_GhostMuonSegmentCount': 'jets_GhostMuonSegmentCount',
    'jets_JVFCorr': 'jets_JVFCorr',
    'jets_JetConstitScaleMomentum_eta': 'jets_JetConstitScaleMomentum_eta',
    'jets_JetConstitScaleMomentum_m': 'jets_JetConstitScaleMomentum_m',
    'jets_JetConstitScaleMomentum_phi': 'jets_JetConstitScaleMomentum_phi',
    'jets_JetConstitScaleMomentum_pt': 'jets_JetConstitScaleMomentum_pt',
    'jets_JvtRpt': 'jets_JvtRpt',
    'jets_fJVT': 'jets_fJVT',
    'jets_passFJVT': 'jets_passFJVT',
    'jets_passJVT': 'jets_passJVT',
    'jets_Timing': 'jets_Timing',
    'jets_Jvt': 'jets_Jvt',
    'jets_EMFrac': 'jets_EMFrac',
    'jets_Width': 'jets_Width',
    'jets_chf': 'jets_chf',
    'jets_eta': r'$|\eta|$',
    'jets_m': 'jets_m',
    'jets_phi': 'jets_phi',
    'jets_pt': r'$p_{\mathrm{T}}$ [GeV]',
    'jets_PFO_n': 'jets_PFO_n',
    'jets_Constituent_n': r'$N_{\mathrm{Const}}$',
    'jets_TopoTower_n': r'$N_{\mathrm{Tower}}$',
    'jets_Constituent_n+jets_TopoTower_n': r'$N_{\mathrm{Const}} + N_{\mathrm{Tower}}$',
    'jets_ChargedPFOWidthPt1000[0]': 'jets_ChargedPFOWidthPt1000',
    'jets_TrackWidthPt1000[0]': 'jets_TrackWidthPt1000',
    'jets_NumChargedPFOPt1000[0]': 'jets_NumChargedPFOPt1000',
    'jets_NumChargedPFOPt500[0]': 'jets_NumChargedPFOPt500',
    'jets_SumPtChargedPFOPt500[0]': 'jets_SumPtChargedPFOPt500',
    'jets_PFO_m': 'jets_PFO_m',
    'jets_PFO_pt': 'jets_PFO_pt',
    'jets_PFO_eta': 'jets_PFO_eta',
    'jets_PFO_phi': 'jets_PFO_phi',
    'corrected_averageInteractionsPerCrossing[0]': r'$\mu$',
    'corrected_averageInteractionsPerCrossing': r'$\mu$',
    'pt_jet': 'pt_jet',
    'eta_jet': 'eta_jet',
    'N_PFO': 'N_PFO',
    'W_PFO_jet': 'W_PFO_jet',
    'C1_PFO_jet': 'C1_PFO_jet',
    'log_pT': r'$\log{p_{\mathrm{T}}}$',
    'log_PT|PTjet': r'$\log{\frac{p_{\mathrm{T}}}{p_{\mathrm{T}}^{\mathrm{jet}}}}$',
    'log_E': r'$\log{E}$',
    'log_E|Ejet': r'$\log{\frac{E}{E^{\mathrm{jet}}}}$',
    'pT': r'$p_{\mathrm{T}}$',
    'PT|PTjet': r'$\frac{p_{\mathrm{T}}}{p_{\mathrm{T}}^{\mathrm{jet}}}$',
    'E': r'$E$',
    'E|Ejet': r'$\frac{E}{E^{\mathrm{jet}}}$',
    'm': r'$m$',
    'deltaEta': r'$\Delta \eta$',
    'deltaPhi': r'$\Delta \phi$',
    'deltaR': r'$\Delta R$',
    'delta': r'$\log{\Delta}$',
    'k_t': r'$\log{k_{\mathrm{T}}}$',
    'z': r'$z$',
    'm2': r'$\log{m^2}$',
    'log_norm_p': r'$\log{\norm{p}}$',
    'is_topo': 'isTopo',
    'loretz_products': '$p_i \cdot p_j$',
}


MODEL_NAMING_SCHEMA = {
    'depart_flat_pT': r'DeParT (Flat $p_{\mathrm{T}}$)',
    'basic_fc': 'FC',
    'depart': 'DeParT',
    'idepart-col_split': 'DeParT (Col. Split)',
    'idepart+topo': 'DeParT (+Topo)',
    'idepart+vbf': 'DeParT (+VBF)',
    "idepart-rel-finetune": "DeParT (F.T.)",
    "idepart-finetunne": "DeParT (F.T.)",
    "idepart-rel-finetunne": "DeParT (F.T.)",
    "idepart-rel-finetune-1": "DeParT (F.T. 1)",
    "idepart-rel-finetune-2": "DeParT (F.T. 2)",
    "idepart-rel-finetune-3": "DeParT (F.T. 3)",
    'idepart+topo+track': 'DeParT (+Topo,Trk)',
    'depart-m': 'DeParT',
    'depart-ircs': 'DeParT (IRC safe)',
    'part': 'nParT',
    'part-m': 'nParT',
    'idepart_rel': 'DeParT (Rel.)',
    'interacting_depart': 'DeParT',
    'idepart': 'DeParT',
    # 'idepart-rel': 'DeParT (Rel.)',
    'idepart-rel': 'DeParT',
    'idepart-rel-allj': 'DeParT',
    'idepart-rel-noTopo': 'DeParT (No Topo)',
    'idepart-rel-80const': 'DeParT (80 Const.)',
    'idepart-rel-UFO': 'DeParT (UFO)',
    'idepart-rel-PFO': 'DeParT (PFO)',
    'idepart-rel-mid': 'DeParT (Mid)',
    'idepart-rel-low': 'DeParT (Low)',
    'idepart-rel-high': 'DeParT (High)',
    'idepart-rel+topo+track': 'DeParT (Rel.,+Topo,Trk)',
    'idepart-rel+topo': 'DeParT (Rel.,+Topo)',
    'idepart-rel2': 'DeParT (Rel.)',
    'idepart-m': 'DeParT',
    'interacting_depart_no_norm': 'DeParT (No Norm)',
    'interacting_part': 'ParT',
    'ipart': 'ParT',
    'ipart-m': 'ParT',
    'ipart+topo': 'ParT (+Topo)',
    'pfn': 'PFN',
    'pfn-rel': 'PFN',
    'pfn-rel-UFO': 'PFN (UFO)',
    'pfn-rel-PFO': 'PFN (PFO)',
    'pfn+topo': 'PFN (+Topo)',
    'pfn-m': 'PFN',
    'efn': 'EFN',
    'efn+topo': 'EFN (+Topo)',
    'transformer': 'Transformer',
    'transformer-m': 'Transformer',
    'bdt': 'BDT',
    'depart_100M': 'DeParT (100M jets)',
    'particle_net': 'P.Net',
    'particle_net-m': 'P.Net',
    'pfn_bad': 'PFN (Bad)',
    'pfn_noW': 'PFN (No W)',
    'fc-full': 'FC (all features)',
    'highway-full': 'Highway (all features)',
    'highway-UFO': 'Highway (UFO)',
    'highway-PFO': 'Highway (PFO)',
    'fc': 'FC',
    'fc-no-eta': 'FC (No $\eta$)',
    'fc-no_eta': 'FC (No $\eta$)',
    'highway': 'Highway',
    'fc_noW': 'FC (No W)',
    'fc-crafted': r'FC red.',
    'fc-reduced': r'FC',
    'fc_crafted': r'FC red.',
    'fc_crafted-UFO': r'FC red. (UFO)',
    'fc_crafted-PFO': r'FC red. (PFO)',
    'fc_crafted-no-eta': r'FC red. (No $\eta$)',
    'fc_crafted-no_eta': r'FC red. (No $\eta$)',
    'fc+topo': r'FC (Topo)',
    'highway-crafted': r'Highway red.',
    'highway_crafted': r'Highway red.',
    'highway-no_eta': r'Highway (No $\eta$)',
    'depart-Pythia8EvtGen_A14NNPDF23LO_jetjet': 'DeParT (Py)',
    'depart-Sh_2211_Enh_clusterTune': 'DeParT (Sh Cl.)',
    'depart-H7EG_jetjet_Cluster': 'DeParT (Hw Ang.)',
    'depart-H7EG_jetjet_Cluster_dipole': 'DeParT (Hw Dip.)',
    'depart-Sherpa_CT10_CT14nnlo_CSShower_Lund_2to2jets': 'DeParT (Sh St.)',
    'depart-Sh_2211_jj_DIRE': 'DeParT (Sh Dire)',
    'depart-PhH7EG_jj': 'DeParT (PhHw)',
    'depart-PhPy8EG_jj': 'DeParT (PhPy)',
    'depart-multiMC': 'DeParT (Multi)',
}


METRIC_NAMING_SCHEMA = {
    'eff_tag_efficiency': r'$\varepsilon_{\mathrm{eff}}$',
    'effective_tagging_efficiency': r'Effective Tagging Efficiency',
    'binary_accuracy': 'Accuracy',
    'accuracy': 'Accuracy',
    'relative_accuracy': 'Accuracy',
    'relative_error': 'Relative Error',
    'heatmap': 'Relative Error',
    'auc': 'AUC',
    'gluon_efficiency': r'$\varepsilon_g$',
    'quark_efficiency': r'$\varepsilon_q$',
    'gluon_rejection': r'$\varepsilon_g^{-1}$',
    'quark_rejection': r'$\varepsilon_q^{-1}$',
    'gluon_rejection_at_quark_80wp': r'$\varepsilon_g^{-1} @ \varepsilon_q = 0.8 $',
    'gluon_rejection_at_quark_50wp': r'$\varepsilon_g^{-1} @ \varepsilon_q = 0.5 $',
    'gluon_efficiency_at_quark_80wp': r'$\varepsilon_g @ \varepsilon_q = 0.8 $',
    'gluon_efficiency_at_quark_50wp': r'$\varepsilon_q @ \varepsilon_g = 0.5 $',
    'quark_efficiency_at_gluon_50wp': r'$\varepsilon_q @ \varepsilon_g = 0.5 $',
    'quark_efficiency_at_gluon_80wp': r'$\varepsilon_q @ \varepsilon_g = 0.8 $',
    'quark_rejection_at_gluon_80wp': r'$\varepsilon_q^{-1} @ \varepsilon_g = 0.8 $',
    'quark_rejection_at_gluon_50wp': r'$\varepsilon_q^{-1} @ \varepsilon_g = 0.5 $',
    'loss': 'Loss',
    'roc': 'ROC',
}

METRIC_NAMING_SCHEMA_NAMED = {
    'eff_tag_efficiency': 'Effective Tagging Efficiency',
    'effective_tagging_efficiency': r'Effective Tagging Efficiency',
    'binary_accuracy': 'Accuracy',
    'accuracy': 'Accuracy',
    'relative_accuracy': 'Accuracy',
    'relative_error': 'Relative Error',
    'heatmap': 'Relative Error',
    'auc': 'AUC',
    'gluon_efficiency': 'Gluon Efficiency',
    'quark_efficiency': 'Quark Efficiency',
    'gluon_rejection': 'Gluon Rejection',
    'quark_rejection': 'Quark Rejection',
    'gluon_rejection_at_quark_80wp': 'Gluon Rejection at Quark 80% WP',
    'gluon_rejection_at_quark_50wp': 'Gluon Rejection at Quark 50% WP',
    'gluon_efficiency_at_quark_80wp': 'Gluon Efficiency at Quark 80% WP',
    'gluon_efficiency_at_quark_50wp': 'Gluon Efficiency at Quark 50% WP',
    'loss': 'Loss',
    'roc': 'ROC',
}

MC_NAMING_SCHEMA = {
    'pythia': 'Py',
    'sherpa_enh_cluster_tune': 'Sh Cl.',
    'sherpa_lund': 'Sh St.',
    'sherpa_dire': 'Sh Dire',
    'herwig': 'Hw Ang.',
    'herwig_dipole': 'Hw Dip.',
    'herwig7': 'Hw Ang.',
    'herwig7_dipole': 'Hw Dip.',
    'sherpa': 'Sherpa Cluster Old',
    'powheg_pythia': 'PhPy',
    'powheg+pythia': 'PhPy',
    'powheg_herwig': 'PhHw',
    'powheg+herwig': 'PhHw',
    'powheg_herwig7': 'PhHw',
    'powheg+herwig7': 'PhHw',
    'Pythia8EvtGen_A14NNPDF23LO_jetjet': 'Pythia',
    'PhPy8EG_A14_ttbar_hdamp258p75_nonallhad': r'$t\bar{t}$ PhPy',
    'PowhegPy8EG_NNLOPS_nnlo_30_ggH125_tautaul13l7': 'H+j PhPy',
    'PowhegPy8EG_NNPDF30_AZNLOCTEQ6L1_VBFH125_tautaul13l7': 'VBF+j PhPy',
    'PowhegPythia8EvtGen_AZNLOCTEQ6L1_Zmumu': 'Z+j PhPy',
    'PowhegPy8EG_NNPDF30_AZNLOCTEQ6L1_VBFH125_tautaul13l7': 'VBF PhPy',
    'Sherpa_222_NNPDF30NNLO_SinglePhoton': '$\gamma$+j Sh',
    'Sh_2211_Enh_clusterTune': 'j+j Sh Cl.',
    'H7EG_jetjet_Cluster': 'j+j Hw Ang.',
    'H7EG_Matchbox_angular_jetjetNLO': 'j+j Hw Ang.',
    'H7EG_Matchbox_dipole_jetjetNLO': 'j+j Hw Dip.',
    'H7EG_jetjet_Cluster_dipole': 'j+j Hw Dip.',
    'Sherpa_CT10_CT14nnlo_CSShower_2to2jets': 'j+j Sh Cl.',
    'Sherpa_CT10_CT14nnlo_CSShower_Lund_2to2jets': 'j+j Sh St.',
    'Sh_2211_jj_DIRE': 'j+j Sh Dire',
    'PhH7EG_jj': 'j+j PhHw',
    'PhPy8EG_jj': 'j+j PhPy',
    'multiMC': 'j+j Multi',
}
