LATEX_NAMING_CONVENTION = {
    'jets_ActiveArea4vec_m': 'jets_ActiveArea4vec_m',
    'jets_ActiveArea4vec_phi': 'jets_ActiveArea4vec_phi',
    'jets_ActiveArea4vec_eta': 'jets_ActiveArea4vec_eta',
    'jets_ActiveArea4vec_pt': 'jets_ActiveArea4vec_pt',
    'jets_DetectorEta': 'jets_DetectorEta',
    'jets_FracSamplingMax': 'jets_FracSamplingMax',
    'jets_FracSamplingMaxIndex': 'jets_FracSamplingMaxIndex',
    'jets_GhostMuonSegmentCount': 'jets_GhostMuonSegmentCount',
    'jets_JVFCorr': 'jets_JVFCorr',
    'jets_JetConstitScaleMomentum_eta': 'jets_JetConstitScaleMomentum_eta',
    'jets_JetConstitScaleMomentum_m': 'jets_JetConstitScaleMomentum_m',
    'jets_JetConstitScaleMomentum_phi': 'jets_JetConstitScaleMomentum_phi',
    'jets_JetConstitScaleMomentum_pt': 'jets_JetConstitScaleMomentum_pt',
    'jets_JvtRpt': 'jets_JvtRpt',
    'jets_fJVT': 'jets_fJVT',
    'jets_passFJVT': 'jets_passFJVT',
    'jets_passJVT': 'jets_passJVT',
    'jets_Timing': 'jets_Timing',
    'jets_Jvt': 'jets_Jvt',
    'jets_EMFrac': 'jets_EMFrac',
    'jets_Width': 'jets_Width',
    'jets_chf': 'jets_chf',
    'jets_eta': r'$|\eta|$',
    'jets_m': 'jets_m',
    'jets_phi': 'jets_phi',
    'jets_pt': r'$p_{\mathrm{T}}$ [TeV]',
    'jets_PFO_n': 'jets_PFO_n',
    'jets_ChargedPFOWidthPt1000[0]': 'jets_ChargedPFOWidthPt1000',
    'jets_TrackWidthPt1000[0]': 'jets_TrackWidthPt1000',
    'jets_NumChargedPFOPt1000[0]': 'jets_NumChargedPFOPt1000',
    'jets_NumChargedPFOPt500[0]': 'jets_NumChargedPFOPt500',
    'jets_SumPtChargedPFOPt500[0]': 'jets_SumPtChargedPFOPt500',
    'jets_PFO_m': 'jets_PFO_m',
    'jets_PFO_pt': 'jets_PFO_pt',
    'jets_PFO_eta': 'jets_PFO_eta',
    'jets_PFO_phi': 'jets_PFO_phi',
    'corrected_averageInteractionsPerCrossing[0]': r'$\mu$',
    'corrected_averageInteractionsPerCrossing': r'$\mu$',
    'pt_jet': 'pt_jet',
    'eta_jet': 'eta_jet',
    'N_PFO': 'N_PFO',
    'W_PFO_jet': 'W_PFO_jet',
    'C1_PFO_jet': 'C1_PFO_jet',
    'log_pT': r'$\log{p_{\mathrm{T}}}$',
    'log_PT|PTjet': r'$\log{\frac{p_{\mathrm{T}}}{p_{\mathrm{T}}^{\mathrm{jet}}}}$',
    'log_E': r'$\log{E}$',
    'log_E|Ejet': r'$\log{\frac{E}{E^{\mathrm{jet}}}}$',
    'pT': r'$p_{\mathrm{T}}$',
    'PT|PTjet': r'$\frac{p_{\mathrm{T}}}{p_{\mathrm{T}}^{\mathrm{jet}}}$',
    'E': r'$E$',
    'E|Ejet': r'$\frac{E}{E^{\mathrm{jet}}}$',
    'm': r'$m$',
    'deltaEta': r'$\Delta \eta$',
    'deltaPhi': r'$\Delta \phi$',
    'deltaR': r'$\Delta R$',
    'delta': r'$\log{\Delta}$',
    'k_t': r'$\log{k_{\mathrm{T}}}$',
    'z': r'$z$',
    'm2': r'$\log{m^2}$',
    'log_norm_p': r'$\log{\norm{p}}$',
}


MODEL_NAMING_SCHEMA = {
    'depart_flat_pT': r'DeParT (Flat $p_{\mathrm{T}}$)',
    'fc': 'Fully Connected',
    'basic_fc': 'Fully Connected',
    'depart': 'nDeParT',
    'part': 'nParT',
    'highway': 'Highway',
    'idepart_rel': 'DeParT (Relative)',
    'interacting_depart': 'DeParT',
    'idepart': 'DeParT',
    'interacting_depart_no_norm': 'DeParT (No Norm)',
    'interacting_part': 'ParT',
    'ipart': 'ParT',
    'pfn': 'PFN',
    'efn': 'EFN',
    'transformer': 'Transformer',
    'bdt': 'BDT',
    'depart_100M': 'DeParT (100M jets)',
    'particle_net': 'ParticleNet',
    'pfn_bad': 'PFN (Bad)',
    'pfn_noW': 'PFN (No W)',
    'fc_noW': 'Fully Connected (No W)',
    'fc_crafted': r'Fully Connected ($C_1$, $w_{\mathrm{PFO}}$, $N_{\mathrm{PFO}}$), $p_{\mathrm{T}}$, $\eta$',
    'highway_crafted': r'Highway ($C_1$, $w_{\mathrm{PFO}}$, $N_{\mathrm{PFO}}$), $p_{\mathrm{T}}$, $\eta$',
}


METRIC_NAMING_SCHEMA = {
    'eff_tag_efficiency': r'$\varepsilon_{\mathrm{eff}}$',
    'effective_tagging_efficiency': r'Effective Tagging Efficiency',
    'binary_accuracy': 'Accuracy',
    'accuracy': 'Accuracy',
    'relative_accuracy': 'Accuracy',
    'relative_error': 'Relative Error',
    'heatmap': 'Relative Error',
    'auc': 'AUC',
    'gluon_efficiency': r'$\varepsilon_g$',
    'quark_efficiency': r'$\varepsilon_q$',
    'gluon_rejection': r'$\varepsilon_g^{-1}$',
    'quark_rejection': r'$\varepsilon_q^{-1}$',
    'gluon_rejection_at_quark_80wp': r'$\varepsilon_g^{-1} @ \varepsilon_q = 0.8 $',
    'gluon_rejection_at_quark_50wp': r'$\varepsilon_g^{-1} @ \varepsilon_q = 0.5 $',
    'gluon_efficiency_at_quark_80wp': r'$\varepsilon_g @ \varepsilon_q = 0.8 $',
    'gluon_efficiency_at_quark_50wp': r'$\varepsilon_q @ \varepsilon_g = 0.5 $',
    'loss': 'Loss',
    'roc': 'ROC',
}

MC_NAMING_SCHEMA = {
    'pythia': 'Pythia',
    'sherpa': 'Sherpa Cluster',
    'sherpa_lund': 'Sherpa String',
    'sherpa_dire': 'Sherpa DIRE',
    'sherpa_enh_cluster_tune': 'Sherpa Tuned',
    'herwig': 'Herwig Angular',
    'herwig_dipole': 'Herwig Dipole',
    'herwig7': 'Herwig Angular',
    'herwig7_dipole': 'Herwig Dipole',
    'powheg_pythia': 'Powheg+Pythia',
    'powheg+pythia': 'Powheg+Pythia',
    'powheg_herwig': 'Powheg+Herwig',
    'powheg+herwig': 'Powheg+Herwig',
    'powheg_herwig7': 'Powheg+Herwig',
    'powheg+herwig7': 'Powheg+Herwig',
}
