defaults:
  # - data: pythia_allJZ
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] - %(message)s"
  output_subdir: config

data:
  path: ./data/pythia_stepwise # Path to data folder containing folder of *.root files.
  target: jets_PartonTruthLabelID
  labels: # list of labels to use.
    - gluon
    - quark
  target_labels:
    - [21]
    - [1, 2, 3, 4, 5, 6]
  variable_unknown_labels: [-1, -999]
  label_weights:
  cut: 
  weight: weight

logdir: logs/stepwise_flat/eval
models_path: logs/stepwise_flat
cache_scores: score_dataset.csv
seed: 42
draw_distribution: 20_000
test_subfolder: test
batch_size: 512
take: 1_000_000
binning:
  variable: 'jets_pt'
  bins: [200000, 300000, 400000, 600000, 850000, 1100000, 1400000, 1750000, 2500000] 
  max_bin: 
  min_bin:
  log_bin_base: 
additional_variables: ['jets_eta', 'JZ_slice', 'corrected_averageInteractionsPerCrossing']
metrics_to_plot:
  [
    "gluon_efficiency", 
    "quark_efficiency",
    "binary_accuracy",
    "auc",
  ]
reference_model: depart
validation_plots_in_bins: False
ylims: # [[0, 1.1], [0, 1.1], [0.5, 1.1], [0.5, 1.1], [0.10, 0.5]]
model_names: [
    # "particle_net",
    # "idepart",
    # "ipart",
    # #
    # "depart",
    # "part",
    # "transformer",
    # "pfn",
    # # 
    # "pfn_bad",
    # #
    # "efn",
    # #
    # "fc-full",
    # "highway-full",
    # "fc_crafted",
    # "highway_crafted",
    # "fc",
    # "highway",
    "depart",
    "depart-coll_split",
    "depart-coll_split-001",
    "depart-coll_split-010",
    "depart-coll_split-030",
    "depart-rot_drop_smear",
    "depart-rotation",
    "depart-soft_drop",
    "depart-soft_drop-01-02",
    "depart-soft_drop-01-05",
    "depart-soft_drop-01-07",
    "depart-soft_drop-100-02",
    "depart-soft_drop-100-05",
    "depart-soft_drop-100-07",
    "depart-soft_drop-10-02",
    "depart-soft_drop-10-05",
    "depart-soft_drop-10-07",
    "depart-soft_smear",
    "depart-soft_smear-10",
    "depart-soft_smear-1000",
    "depart-ircs",
    "depart-no-int",
    "pfn",
    "fc_crafted",

  ]
model_input_types: [
    # "gnn",
    # "interaction_constituents",
    # "interaction_constituents",
    # #
    # "constituents",
    # "constituents",
    # "constituents",
    # "constituents",
    # #
    # "irc",
    # #
    # "irc_safe",
    # #
    # "full_highlevel",
    # "full_highlevel",
    # "crafted_highlevel",
    # "crafted_highlevel",
    # "highlevel",
    # "highlevel",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "interaction_constituents",
    "ircs_constituents",
    "constituents",
    "constituents",
    "crafted_highlevel",
  ]
working_point_path: # good_logs/cpre
working_point_file_name:
threads: