defaults:
  # - data: pythia_allJZ
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] - %(message)s"
  output_subdir: config

data:
  path: ./data/pythia_stepwise # Path to data folder containing folder of *.root files.
  target: jets_PartonTruthLabelID
  labels: # list of labels to use.
    - gluon
    - quark
  target_labels:
    - [21]
    - [1, 2, 3, 4, 5, 6]
  variable_unknown_labels: [-1, -999]
  label_weights:
  cut: jets_PFO_n<100
  cached:
  weight: #weight

logdir: logs/stepwise_flat/eval
models_path: logs/stepwise_flat
seed: 42
draw_distribution: 400_000
test_subfolder: test
batch_size: 384
take: 500_000
binning:
  variable: jets_pt
  bins: 10
  max_bin: 2_500_000
  min_bin: 60_000
  log_bin_base: 0
metrics_to_plot:
  [
    "gluon_efficiency",
    "quark_efficiency",
    "binary_accuracy",
    "auc",
    "effective_tagging_efficiency",
  ]
reference_model: transformer
validation_plots_in_bins: False
ylims: # [[0, 1.1], [0, 1.1], [0.5, 1.1], [0.5, 1.1], [0.10, 0.5]]
model_names: [
    "idepart",
    "ipart",
    #
    # "idepart_rel",
    #
    "depart",
    "part",
    "transformer",
    "pfn",
    #
    "efn",
    
    "fc",
    "highway",
  ]
model_input_types: [
    "interaction_constituents",
    "interaction_constituents",
    #
    # "irelative_constituents",
    #
    "constituents",
    "constituents",
    "constituents",
    "constituents",
    #
    "irc_safe",
    
    "highlevel",
    "highlevel",
  ]
working_point_path: # good_logs/cpre
working_point_file_name:
threads:
