defaults:
  # - data: pythia_allJZ
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] - %(message)s"
  output_subdir: config

data:
  path: ./data/pythia_stepwise # Path to data folder containing folder of *.root files.
  target: jets_PartonTruthLabelID
  labels: # list of labels to use.
    - gluon
    - quark
  target_labels:
    - [21]
    - [1, 2, 3, 4, 5, 6]
  variable_unknown_labels: [-1, -999]
  label_weights:
  cut:
  weight: weight

logdir: logs/stepwise_flat/eval
models_path: logs/stepwise_flat
cache_scores: score_dataset.csv
seed: 42
draw_distribution: 20_000
test_subfolder: test
batch_size: 512
take: 1_124_739
binning:
  variable: jets_eta
  bins: 10
  max_bin: 4 #4_600_000
  min_bin: -4 #60_000
  log_bin_base:
metrics_to_plot:
  ["gluon_efficiency", "quark_efficiency", "binary_accuracy", "auc"]
reference_model: transformer
validation_plots_in_bins: False
ylims: # [[0, 1.1], [0, 1.1], [0.5, 1.1], [0.5, 1.1], [0.10, 0.5]]
model_names: [
    "particle_net",
    #
    "idepart",
    "ipart",
    #
    # "idepart_rel",
    #
    "depart",
    "part",
    "transformer",
    "pfn",
    #
    "efn",
    #
    "fc",
    "highway",
    #
  ]
model_input_types: [
    "gnn",
    #
    "interaction_constituents",
    "interaction_constituents",
    #
    # "irelative_constituents",
    #
    "constituents",
    "constituents",
    "constituents",
    "constituents",
    #
    "irc_safe",
    #
    "highlevel",
    "highlevel",
    #
  ]
working_point_path: # good_logs/cpre
working_point_file_name:
threads: