defaults:
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] - %(message)s"
  output_subdir: config

data:
  path: 
  target: jets_PartonTruthLabelID
  labels: # list of labels to use.
    - gluon
    - quark
  target_labels:
    - [21]
    - [1, 2, 3, 4, 5, 6]
  variable_unknown_labels: [-1, -999]
  label_weights:
  cut: 
  weight: weight

logdir: logs/eval_test/idepart-rel
model_path: 
cache_scores: score_dataset.csv
seed: 42
draw_distribution: 
test_subfolder: 
batch_size: 1024
take: 5000000
include_variables:
  - jets_pt
  - jets_eta
  - corrected_averageInteractionsPerCrossing
  - jets_TopoTower_n
  - jets_Constituent_n
  - jets_index
validation_plots_in_bins: False
model_name: idepart-rel
model_input_type: 
working_point_path: 
threads: