defaults:
  - data: data2
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[${now:%Y-%m-%d}  ${now:%H:%M:%S}][%(levelname)s] - %(message)s"
  output_subdir: config

base_logdir: logs # Base log directory for all runs.
logdir: ${base_logdir}/eval
model_dir: ${base_logdir}/model
draw_distribution: 100_000
feature_importance: False # Whether to draw feature importance.
test_subfolder: test
seed: 42
test_sample_cuts:
  - "(jets_pt>20_000) && (jets_pt<60_000)"
  - "(jets_pt>60_000) && (jets_pt<160_000)"
  - "(jets_pt>160_000) && (jets_pt<400_000)"
  - "(jets_pt>400_000) && (jets_pt<800_000)"
  - "(jets_pt>800_000)"
batch_size: 512
take: 1_000_000
model: highway
