defaults:
  - data: data2
  - binning: pT
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[%(asctime)s][%(levelname)s] - %(message)s"
  output_subdir: config

base_logdir: logs # Base log directory for all runs.
eval_logs: eval # Log directory for eval runs.
logdir: ${base_logdir}/${eval_logs} # Log directory for eval runs.
model_dir: ${base_logdir}/model
draw_distribution: 5_000
feature_importance: False # Whether to draw feature importance.
test_subfolder: test
seed: 42
batch_size: 256
take: 50_000
model: highway
interaction: False
relative: False
threshold: 0.5
old: False
include_base: True