defaults:
  - data: data1_small
  - _self_

hydra:
  run:
    dir: ${logdir}
  sweep:
    dir: ${logdir}
    subdir: ${hydra.job.num}
  job_logging:
    formatters:
      simple:
        format: "[${now:%Y-%m-%d}  ${now:%H:%M:%S}][%(levelname)s] - %(message)s"
  output_subdir: config

draw_distribution: 0
test_subfolder: test
seed: 42
logdir: "logs/eval"
model_dir: "/Users/samueljankovych/Documents/MFF/bakalarka/JIDENN/logs/2022-10-27__09_38_42/model"
test_sample_cuts:
  # - "(jets_pt>20_000) && (jets_pt<60_000)"
  # - jets_pt>60_000
batch_size: 64
take: 1_000
