test_sample_cuts:
  - "(jets_pt>20_000) && (jets_pt<60_000) && (jets_passFJVT==1) && (jets_passJVT==1) && (jets_Jvt>0.95) && (jets_PFO_n>5)"
  - "(jets_pt>60_000) && (jets_pt<160_000) && (jets_passFJVT==1) && (jets_passJVT==1) && (jets_Jvt>0.95) && (jets_PFO_n>5)"
  - "(jets_pt>160_000) && (jets_pt<400_000) && (jets_passFJVT==1) && (jets_passJVT==1) && (jets_Jvt>0.95) && (jets_PFO_n>5)"
  - "(jets_pt>400_000) && (jets_pt<800_000) && (jets_passFJVT==1) && (jets_passJVT==1) && (jets_Jvt>0.95) && (jets_PFO_n>5)"
  - "(jets_pt>800_000) && (jets_passFJVT==1) && (jets_passJVT==1) && (jets_Jvt>0.95) && (jets_PFO_n>5)"

test_names:
  - "20-60"
  - "60-160"
  - "160-400"
  - "400-800"
  - "800-"
