test_sample_cuts:
  - "(jets_pt>20_000) && (jets_pt<30_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>30_000) && (jets_pt<40_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>40_000) && (jets_pt<60_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>60_000) && (jets_pt<100_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>100_000) && (jets_pt<150_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>150_000) && (jets_pt<200_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>200_000) && (jets_pt<300_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>300_000) && (jets_pt<400_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>400_000) && (jets_pt<500_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>500_000) && (jets_pt<600_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>600_000) && (jets_pt<800_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>800_000) && (jets_pt<1_000_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>1_000_000) && (jets_pt<1_200_000) && (jets_eta<2.1) && (jets_eta>-2.1)"
  - "(jets_pt>1_200_000) && (jets_eta<2.1) && (jets_eta>-2.1)"

test_names:
  - "20-30"
  - "30-40"
  - "40-60"
  - "60-100"
  - "100-150"
  - "150-200"
  - "200-300"
  - "300-400"
  - "400-500"
  - "500-600"
  - "600-800"
  - "800-1000"
  - "1000-1200"
  - "1200+"
